FROM nikonyrh/spark_ocv_base
MAINTAINER Niko Nyrh "https://github.com/nikonyrh"

# to build: docker build -t nikonyrh/spark spark_cusom

RUN /bin/bash -c "source /py3/bin/activate && pip install msgpack-python"

